# physical traits source: https://www.bryndonovan.com/
eye_shape = [
    'large',
    'small',
    'narrow',
    'sharp',
    'squinty',
    'round',
    'wide-set',
    'close-set',
    'deep-set',
    'sunken',
    'bulging',
    'protruding',
    'wide',
    'hooded',
    'heavy-lidded',
    'bedroom',
    'bright',
    'sparkling',
    'glittering',
    'flecked',
    'dull',
    'bleary',
    'rheumy',
    'cloudy',
    'red-rimmed',
    'beady',
    'birdlike',
    'cat-like',
    'jewel-like',
    'steely',
    'hard',
    'long-lashed',
    'thick-lashed',
    'thin-lashed',
]

eye_color = [
    'chestnut',
    'chocolate brown',
    'cocoa brown',
    'coffee brown',
    'mocha',
    'mahogany',
    'sepia',
    'sienna brown',
    'mink brown',
    'copper',
    'amber',
    'cognac-colored',
    'whiskey-colored',
    'brandy-colored',
    'honey',
    'tawny',
    'topaz',
    'hazel',
    'obsidian',
    'onyx',
    'coal',
    'raven',
    'midnight',
    'sky blue',
    'sunny blue',
    'cornflower blue',
    'steel blue',
    'ice blue',
    'Arctic blue',
    'glacial blue',
    'crystal blue',
    'cerulean',
    'electric blue',
    'azure',
    'lake blue',
    'aquamarine',
    'turquoise',
    'denim blue',
    'slate blue',
    'slate gray',
    'storm blue',
    'storm gray',
    'smoky gray',
    'ash gray',
    'concrete gray',
    'dove gray',
    'fog gray',
    'gunmetal gray',
    'olive',
    'emerald',
    'leaf green',
    'moss green',
]

skin_color = [
    'amber',
    'bronze',
    'cinnamon',
    'copper',
    'dark brown',
    'deep brown',
    'ebony',
    'honey',
    'golden',
    'pale',
    'pallid',
    'pasty',
    'fair',
    'light',
    'creamy',
    'alabaster',
    'ivory',
    'bisque',
    'milky-white',
    'porcelain',
    'chalky',
    'sallow',
    'olive',
    'peach-colored',
    'rosy',
    'ruddy',
    'florid',
    'russet',
    'tawny',
    'fawny',
]

skin_tone = [
    'lined',
    'wrinkled',
    'seamed',
    'leathery',
    'sagging',
    'drooping',
    'loose',
    'clear',
    'smooth',
    'silken',
    'satiny',
    'dry',
    'flaky',
    'scaly',
    'delicate',
    'thin',
    'translucent',
    'luminescent',
    'baby-soft',
    'flawless',
    'poreless',
    'with large pores',
    'glowing',
    'dewy',
    'dull',
    'velvety',
    'fuzzy',
    'rough',
    'uneven',
    'mottled',
    'dimpled',
    'doughy',
    'firm',
    'freckled',
    'pimply',
    'pockmarked',
    'blemished',
    'pitted',
    'scarred',
    'bruised',
    'veined',
    'scratched',
    'sunburned',
    'weather-beaten',
    'raw',
    'tattooed',
]

hair_color = [
    'black',
    'blue-black',
    'jet black',
    'raven',
    'ebony',
    'inky black',
    'midnight',
    'sable',
    'salt and pepper',
    'silver',
    'charcoal gray',
    'steel gray',
    'white',
    'snow-white',
    'brown',
    'brunette',
    'chocolate-brown',
    'coffee-brown',
    'ash-brown',
    'brown sugar',
    'nut-brown',
    'caramel',
    'tawny-brown',
    'toffee-brown',
    'red',
    'ginger',
    'scarlet',
    'auburn',
    'copper',
    'strawberry blonde',
    'butterscotch',
    'honey',
    'wheat',
    'blonde',
    'golden',
    'sandy blond',
    'flaxen',
    'fair-haired',
    'bleached',
    'platinum',
]

face = [
    'square',
    'round',
    'oblong',
    'oval',
    'elongated',
    'narrow',
    'heart-shaped',
    'catlike',
    'wolfish',
    'chiseled',
    'sculpted',
    'craggy',
    'soft',
    'jowly',
 ]

facial_structure = [
    'a high forehead',
    'a broad forehead',
    'a prominent ridge',
    'a protruding brow',
    'a square jaw',
    'a jutting chin',
    'a pointed chin',
    'a weak chin',
    'a receding chin',
    'a double chin',
    'a cleft chin',
    'a dimpled chin',
    'sharp cheekbones',
    'high cheekbones',
    'angular cheekbones',
    'hollow cheeks',
]

hair_style = [
    'long',
    'short',
    'shoulder-length',
    'loose',
    'limp',
    'dull',
    'shiny',
    'glossy',
    'sleek',
    'smooth',
    'luminous',
    'lustrous',
    'spiky',
    'stringy',
    'shaggy',
    'tangled',
    'messy',
    'tousled',
    'windblown',
    'unkempt',
    'bedhead',
    'straggly',
    'neatly combed',
    'parted',
    'slicked down',
    'slicked back',
    'cropped',
    'clipped',
    'buzz cut',
    'crewcut',
    'bob',
    'mullet',
    'curly',
    'bushy',
    'frizzy',
    'wavy',
    'straight',
    'lanky',
    'dry',
    'oily',
    'greasy',
    'layered',
    'corkscrewed',
    'spiraling',
    'ringlets of',
    'braided',
    'widow’s peak',
    'bald',
    'shaved',
    'comb-over',
    'afro',
    'thick',
    'luxuriant',
    'voluminous',
    'full',
    'wild',
    'untamed',
    'bouncy',
    'wispy',
    'fine',
    'thinning',
]


body = [
    'tall',
    'short',
    'petite',
    'tiny',
    'compact',
    'big',
    'large',
    'burly',
    'beefy',
    'bulky',
    'brawny',
    'barrel-chested',
    'heavy',
    'heavy-set',
    'fat',
    'overweight',
    'obese',
    'flabby',
    'chunky',
    'chubby',
    'pudgy',
    'pot-bellied',
    'portly',
    'thick',
    'stout',
    'lush',
    'plush',
    'full-figured',
    'ample',
    'rounded',
    'generous',
    'voluptuous',
    'curvy',
    'hourglass',
    'plump',
    'leggy',
    'long-legged',
    'gangling',
    'lanky',
    'coltish',
    'lissome',
    'willowy',
    'lithe',
    'lean',
    'slim',
    'slender',
    'trim',
    'thin',
    'skinny',
    'emaciated',
    'gaunt',
    'bony',
    'spare',
    'solid',
    'stocky',
    'wiry',
    'rangy',
    'sinewy',
    'stringy',
    'ropy',
    'sturdy',
    'strapping',
    'powerful',
    'hulking',
    'fit',
    'athletic',
    'toned',
    'built',
    'muscular',
    'chiseled',
    'taut',
    'ripped',
    'Herculean',
    'broad-shouldered',
    'sloping shoulders',
    'bowlegged',
]

facial_hair = [
    'a scar on the left cheek',
    'a scar on the right cheek',
    'a scar above the left eye',
    'a scar above the right eye',
    'a scar on the chin',
    'no facial hair',
    'a thin beard',
    'a wild beard',
    'an unkept beard',
    'a neatly-trimmed beard',
    'a van dyke beard',
    'a goatee and moustache',
    'a chin-strap beard',
    'a long, braided goatee',
    'a neckbeard',
    'a thin layer of peach fuzz beard',
    'a small mole above the lip',
    'a large mole next to the nose',
    'a goatee',
    'a moustache',
    'sideburns',
    'mutton-chop sideburns',
    'stubble',
    'five o’ clock shadow',
]

lips = [
    'thin',
    'narrow',
    'full',
    'lush',
    'Cupid’s bow',
    'rosebud',
    'dry',
    'cracked',
    'chapped',
    'moist',
    'glossy',
]

teeth = [
    'straight',
    'gapped',
    'gleaming white',
    'broken',
    'crooked',
    'missing'
]

nose = [
    'snub',
    'dainty',
    'button',
    'turned-up',
    'long',
    'broad',
    'thin',
    'straight',
    'pointed',
    'crooked',
    'aquiline',
    'Roman',
    'bulbous',
    'flared',
    'hawk',
    'strong',
]

eyebrows = [
    'arched',
    'straight',
    'plucked',
    'sparse',
    'trim',
    'dark',
    'faint',
    'thin',
    'thick',
    'unruly',
    'bushy',
    'heavy',
]

age = [
    'young',
    'stripling',
    'adolescent',
    'youthful',
    'youngish',
    'adult',
    'ageless',
    'mature',
    'middle-aged',
    'aging',
    'elderly',
    'old',
    'wizened',
    'ancient',
]

voice = [
    'breathy',
    'slow',
    'fast',
    'clipped',
    'drawling',
    'considered',
    'babbling',
    'taciturn',
    'mush-mouth',
    'basso',
    'tenor',
    'soprano'
]


# source: http://weirdzine.com/wp-content/uploads/2015/09/Flaws.pdf
flaws = [
    "I judge others harshly, and myself even more severely.",
    "I put too much trust in those who wield power within my temple's hierarchy.",
    "My piety sometimes leads me to blindly trust those that profess faith in my god.",
    "I am inflexible in my thinking.",
    "I am suspicious of strangers and suspect the worst of them.",
    "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.",
    "I can't resist a pretty face.",
    "I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.",
    "I'm convinced that no one could ever fool me in the way I fool others.",
    "I'm too greedy for my own good. I can't resist taking a risk if there's money involved.",
    "I can't resist swindling people who are more powerful than me.",
    "I hate to admit it and will hate myself for it, but I'll run and preserve my own hide if the going gets tough.",
    "When I see something valuable, I can't think about anything but how to steal it.",
    "When faced with a choice between money and my friends, I usually choose the money.",
    "If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.",
    "I have a 'tell' that reveals when I'm lying.",
    "I turn tail and run when things go bad.",
    "An innocent person is in prison for a crime that I committed. I'm okay with that.",
    "I'll do anything to win fame and renown.",
    "I'm a sucker for a pretty face.",
    "A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.",
    "I once satirized a noble who still wants my head. It was a mistake that I will likely repeat.",
    "I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble.",
    "Despite my best efforts, I am unreliable to my friends.",
    "The tyrant who rules my land will stop at nothing to see me killed.",
    "I'm convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.",
    "The people who knew me when I was young know my shameful secret, so I can never go home again.",
    "I have a weakness for the vices of the city, especially hard drink.",
    "Secretly, I believe that things would be better if I were a tyrant lording over the land.",
    "I have trouble trusting in my allies.",
    "I'll do anything to get my hands on something rare or priceless.",
    "I'm quick to assume that someone is trying to cheat me.",
    "No one must ever learn that I once stole money from guild coffers.",
    "I'm never satisfied with what I have--I always want more.",
    "I would kill to acquire a noble title.",
    "I'm horribly jealous of anyone who outshines my handiwork. Everywhere I go, I'm surrounded by rivals.",
    "Now that I've returned to the world, I enjoy its delights a little too much.",
    "I harbor dark bloodthirsty thoughts that my isolation failed to quell.",
    "I am dogmatic in my thoughts and philosophy.",
    "I let my need to win arguments overshadow friendships and harmony.",
    "I'd risk too much to uncover a lost bit of knowledge.",
    "I like keeping secrets and won't share them with anyone.",
    "I secretly believe that everyone is beneath me.",
    "I hide a truly scandalous secret that could ruin my family forever.",
    "I too often hear veiled insults and threats in every word addressed to me, and I'm quick to anger.",
    "I have an insatiable desire for carnal pleasures.",
    "In fact, the world does revolve around me.",
    "By my words and actions, I often bring shame to my family.",
    "I am too enamored of ale, wine, and other intoxicants.",
    "There's no room for caution in a life lived to the fullest.",
    "I remember every insult I've received and nurse a silent resentment toward anyone who's ever wronged me.",
    "I am slow to trust members of other races",
    "Violence is my answer to almost any challenge.",
    "Don't expect me to save those who can't save themselves. It is natural the strong thrive and the weak perish.",
    "I am easily distracted by the promise of information.",
    "Most people scream and run when they see a demon. I stop and take notes on its anatomy.",
    "Unlocking an ancient mystery is worth the price of a civilization.",
    "I overlook obvious solutions in favor of complicated ones.",
    "I speak without really thinking through my words, invariably insulting others.",
    "I can't keep a secret to save my life, or anyone else's.",
    "I follow orders, even if I think they're wrong.",
    "I'll say anything to avoid having to do extra work.",
    "Once someone questions my courage, I never back down no matter how dangerous the situation.",
    "Once I start drinking, it's hard for me to stop.",
    "I can't help but pocket loose coins and other trinkets I come across.",
    "My pride will probably lead to my destruction",
    "The monstrous enemy we faced in battle still leaves me quivering with fear.",
    "I have little respect for anyone who is not a proven warrior.",
    "I made a terrible mistake in battle that cost many lives--and I would do anything to keep that mistake secret.",
    "My hatred of my enemies is blind and unreasoning.",
    "I obey the law, even if the law causes misery.",
    "I'd rather eat my armor than admit when I'm wrong.",
    "If I'm outnumbered, I always run away from a fight.",
    "Gold seems like a lot of money to me, and I'll do just about anything for more of it.",
    "I will never fully trust anyone other than myself.",
    "I'd rather kill someone in their sleep than fight fair.",
    "It's not stealing if I need it more than someone else.",
    "People who don't take care of themselves get what they deserve.",
]

# source: https://www.fantasynamegenerators.com/
goals = [
    "Find a more interesting life",
    "Find a thrilling life",
    "Abandon an ideology",
    "Answer a call to adventure",
    "Apologize",
    "Appease a god",
    "Appease the gods",
    "Avenge a family member",
    "Avenge a friend",
    "Avoid a person",
    "Avoid failure",
    "Avoid responsibilities",
    "Be a better person",
    "Be a hero",
    "Be a master in my field",
    "Be able to eat",
    "Be accepted by society",
    "Be admired",
    "Be amused",
    "Be better than my rival",
    "Be forgiven",
    "Be in control",
    "Be left alone",
    "Be loved",
    "Be redeemed",
    "Be remembered",
    "Be respected",
    "Be self-sufficient",
    "Be somebody else",
    "Be strong",
    "Be the best they can be",
    "Become a leader",
    "Become anonymous",
    "Become famous",
    "Become godly",
    "Become powerful",
    "Become the strongest",
    "Belong somewhere",
    "Better themselves",
    "Break a habit",
    "Break an addiction",
    "Build my own home",
    "Cause mayhem",
    "Change a law",
    "Change the future",
    "Change the past",
    "Clear a family member's name",
    "Clear a friend's name",
    "Clear my name",
    "Complete a collection",
    "Conquer my fear",
    "Consume everything",
    "Create a safe world",
    "Create a utopia",
    "Create a work of art",
    "Cure a strange disease",
    "Destroy corruption",
    "Destroy evil",
    "Discover a new planet",
    "Do nothing",
    "Do the impossible",
    "Do the right thing",
    "Eliminate evil",
    "End a war",
    "End suffering of all",
    "End the conflict",
    "End the suffering of a family member",
    "End the suffering of a friend",
    "Entertain others",
    "Escape a bad situation",
    "Escape death",
    "Escape from my current life",
    "Escape my destiny",
    "Establish my own country",
    "Experience a new culture",
    "Experience something new",
    "Explore the oceans",
    "Explore the unexplored",
    "Feel like they're worth something",
    "Fight for my homeland",
    "Find a cure",
    "Find a dream job",
    "Find a job",
    "Find a legendary creature",
    "Find a lost friend",
    "Find a lost lover",
    "Find a new creative outlet",
    "Find a new home",
    "Find a new passion",
    "Find a purpose",
    "Find a purpose in life",
    "Find beauty",
    "Find excitement",
    "Find inspiration",
    "Find love",
    "Find out a secret",
    "Find out the fate of a family member",
    "Find out the fate of a friend",
    "Find out my true identity",
    "Find peace within",
    "Find romance",
    "Find my muse",
    "Find true love",
    "Fix a mistake",
    "Follow orders",
    "Forget my past",
    "Forgive somebody",
    "Free the animals",
    "Fulfill a destiny",
    "Gain the approval of somebody",
    "Gain what somebody else has",
    "Get away from my past",
    "Get rich",
    "Go on an adventure",
    "Have a passionate relationship",
    "Have fun",
    "Have justice done",
    "Have more and more",
    "Have my work recognized",
    "Have what others have",
    "Have what they can never have",
    "Have what they can't have",
    "Lead a rebellion",
    "Lift a curse",
    "Live",
    "Live a quiet life",
    "Live dangerously",
    "Live forever",
    "Live in peace",
    "Make a difference",
    "Make a sacrifice for the greater good",
    "Make a scientific breakthrough",
    "Make friends",
    "Make people smile",
    "Make sure justice prevails",
    "More power",
    "Never be hurt again",
    "No longer be afraid",
    "No longer be bored",
    "Overcome a death sentence",
    "Overcome a disability",
    "Overcome mockery from the past",
    "Overcome stress",
    "Overthrow the government",
    "Protect a family member",
    "Protect a friend",
    "Protect nature",
    "Protect the innocent",
    "Protect the peace",
    "Protect the planet",
    "Protect my business",
    "Protect my family",
    "Protect my home",
    "Protect my honor",
    "Prove a theory",
    "Prove them wrong",
    "Reach perfection",
    "Reach the promised lands",
    "Reconcile with a person",
    "Redeem somebody",
    "Regain my honor",
    "Remain hidden",
    "Repay a debt",
    "Repay a life debt",
    "Resolve my guilt",
    "Restart the world",
    "Retrieve a lost item",
    "Retrieve a stolen item",
    "Reunite with a family member",
    "Reunite with a lost friend",
    "Revenge",
    "Rid the world of evil",
    "Rule the city",
    "Run for the borders",
    "Satisfy my curiosity",
    "Save Christmas",
    "Save a deity",
    "See others suffer",
    "See the gods pay for my crimes",
    "See the world",
    "Solve a mystery",
    "Solve an ancient mystery",
    "Spread chaos",
    "Spread joy",
    "Spread my ideology",
    "Stand out from the crowd",
    "Start a business",
    "Start a family",
    "Start a new world",
    "Stop a criminal",
    "Take a new direction in life",
    "Thwart destiny",
    "To fit in",
    "Travel back into the past",
    "Travel in space",
    "Travel into the future",
    "Uncover a secret plot",
    "Win a competition",
    "Win a game",
    "Write a book"
]

# source: http://ideonomy.mit.edu/essays/traits.html
personality = [
    'Accessible',
    'Active',
    'Adaptable',
    'Admirable',
    'Adventurous',
    'Agreeable',
    'Alert',
    'Allocentric',
    'Amiable',
    'Anticipative',
    'Appreciative',
    'Articulate',
    'Aspiring',
    'Athletic',
    'Attractive',
    'Balanced',
    'Benevolent',
    'Brilliant',
    'Calm',
    'Capable',
    'Captivating',
    'Caring',
    'Challenging',
    'Charismatic',
    'Charming',
    'Cheerful',
    'Clean',
    'Clear-headed',
    'Clever',
    'Colorful',
    'Companionly',
    'Compassionate',
    'Conciliatory',
    'Confident',
    'Conscientious',
    'Considerate',
    'Constant',
    'Contemplative',
    'Cooperative',
    'Courageous',
    'Courteous',
    'Creative',
    'Cultured',
    'Curious',
    'Daring',
    'Debonair',
    'Decent',
    'Decisive',
    'Dedicated',
    'Deep',
    'Dignified',
    'Directed',
    'Disciplined',
    'Discreet',
    'Dramatic',
    'Dutiful',
    'Dynamic',
    'Earnest',
    'Ebullient',
    'Educated',
    'Efficient',
    'Elegant',
    'Eloquent',
    'Empathetic',
    'Energetic',
    'Enthusiastic',
    'Esthetic',
    'Exciting',
    'Extraordinary',
    'Fair',
    'Faithful',
    'Farsighted',
    'Felicific',
    'Firm',
    'Flexible',
    'Focused',
    'Forecful',
    'Forgiving',
    'Forthright',
    'Freethinking',
    'Friendly',
    'Fun-loving',
    'Gallant',
    'Generous',
    'Gentle',
    'Genuine',
    'Good-natured',
    'Gracious',
    'Hardworking',
    'Healthy',
    'Hearty',
    'Helpful',
    'Herioc',
    'High-minded',
    'Honest',
    'Honorable',
    'Humble',
    'Humorous',
    'Idealistic',
    'Imaginative',
    'Impressive',
    'Incisive',
    'Incorruptible',
    'Independent',
    'Individualistic',
    'Innovative',
    'Inoffensive',
    'Insightful',
    'Insouciant',
    'Intelligent',
    'Intuitive',
    'Invulnerable',
    'Kind',
    'Knowledge',
    'Leaderly',
    'Leisurely',
    'Liberal',
    'Logical',
    'Lovable',
    'Loyal',
    'Lyrical',
    'Magnanimous',
    'Many-sided',
    'Masculine',
    'Manly',
    'Mature',
    'Methodical',
    'Maticulous',
    'Moderate',
    'Modest',
    'Multi-leveled',
    'Neat',
    'Nonauthoritarian',
    'Objective',
    'Observant',
    'Open',
    'Optimistic',
    'Orderly',
    'Organized',
    'Original',
    'Painstaking',
    'Passionate',
    'Patient',
    'Patriotic',
    'Peaceful',
    'Perceptive',
    'Perfectionist',
    'Personable',
    'Persuasive',
    'Planful',
    'Playful',
    'Polished',
    'Popular',
    'Practical',
    'Precise',
    'Principled',
    'Profound',
    'Protean',
    'Protective',
    'Providential',
    'Prudent',
    'Punctual',
    'Pruposeful',
    'Rational',
    'Realistic',
    'Reflective',
    'Relaxed',
    'Reliable',
    'Resourceful',
    'Respectful',
    'Responsible',
    'Responsive',
    'Reverential',
    'Romantic',
    'Rustic',
    'Sage',
    'Sane',
    'Scholarly',
    'Scrupulous',
    'Secure',
    'Selfless',
    'Self-critical',
    'Self-defacing',
    'Self-denying',
    'Self-reliant',
    'Self-sufficent',
    'Sensitive',
    'Sentimental',
    'Seraphic',
    'Serious',
    'Sexy',
    'Sharing',
    'Shrewd',
    'Simple',
    'Skillful',
    'Sober',
    'Sociable',
    'Solid',
    'Sophisticated',
    'Spontaneous',
    'Sporting',
    'Stable',
    'Steadfast',
    'Steady',
    'Stoic',
    'Strong',
    'Studious',
    'Suave',
    'Subtle',
    'Sweet',
    'Sympathetic',
    'Systematic',
    'Tasteful',
    'Teacherly',
    'Thorough',
    'Tidy',
    'Tolerant',
    'Tractable',
    'Trusting',
    'Uncomplaining',
    'Understanding',
    'Undogmatic',
    'Unfoolable',
    'Upright',
    'Urbane',
    'Venturesome',
    'Vivacious',
    'Warm',
    'Well-bred',
    'Well-read',
    'Well-rounded',
    'Winning',
    'Wise',
    'Witty',
    'Youthful',
    'Absentminded',
    'Aggressive',
    'Ambitious',
    'Amusing',
    'Artful',
    'Ascetic',
    'Authoritarian',
    'Big-thinking',
    'Boyish',
    'Breezy',
    'Businesslike',
    'Busy',
    'Casual',
    'Crebral',
    'Chummy',
    'Circumspect',
    'Competitive',
    'Complex',
    'Confidential',
    'Conservative',
    'Contradictory',
    'Crisp',
    'Cute',
    'Deceptive',
    'Determined',
    'Dominating',
    'Dreamy',
    'Driving',
    'Droll',
    'Dry',
    'Earthy',
    'Effeminate',
    'Emotional',
    'Enigmatic',
    'Experimental',
    'Familial',
    'Folksy',
    'Formal',
    'Freewheeling',
    'Frugal',
    'Glamorous',
    'Guileless',
    'High-spirited',
    'Huried',
    'Hypnotic',
    'Iconoclastic',
    'Idiosyncratic',
    'Impassive',
    'Impersonal',
    'Impressionable',
    'Intense',
    'Invisible',
    'Irreligious',
    'Irreverent',
    'Maternal',
    'Mellow',
    'Modern',
    'Moralistic',
    'Mystical',
    'Neutral',
    'Noncommittal',
    'Noncompetitive',
    'Obedient',
    'Old-fashined',
    'Ordinary',
    'Outspoken',
    'Paternalistic',
    'Physical',
    'Placid',
    'Political',
    'Predictable',
    'Preoccupied',
    'Private',
    'Progressive',
    'Proud',
    'Pure',
    'Questioning',
    'Quiet',
    'Religious',
    'Reserved',
    'Restrained',
    'Retiring',
    'Sarcastic',
    'Self-conscious',
    'Sensual',
    'Skeptical',
    'Smooth',
    'Soft',
    'Solemn',
    'Solitary',
    'Stern',
    'Stoiid',
    'Strict',
    'Stubborn',
    'Stylish',
    'Subjective',
    'Surprising',
    'Soft',
    'Tough',
    'Unaggressive',
    'Unambitious',
    'Unceremonious',
    'Unchanging',
    'Undemanding',
    'Unfathomable',
    'Unhurried',
    'Uninhibited',
    'Unpatriotic',
    'Unpredicatable',
    'Unreligious',
    'Unsentimental',
    'Whimsical',
    'Abrasive',
    'Abrupt',
    'Agonizing',
    'Aimless',
    'Airy',
    'Aloof',
    'Amoral',
    'Angry',
    'Anxious',
    'Apathetic',
    'Arbitrary',
    'Argumentative',
    'Arrogantt',
    'Artificial',
    'Asocial',
    'Assertive',
    'Astigmatic',
    'Barbaric',
    'Bewildered',
    'Bizarre',
    'Bland',
    'Blunt',
    'Biosterous',
    'Brittle',
    'Brutal',
    'Calculating',
    'Callous',
    'Cantakerous',
    'Careless',
    'Cautious',
    'Charmless',
    'Childish',
    'Clumsy',
    'Coarse',
    'Cold',
    'Colorless',
    'Complacent',
    'Complaintive',
    'Compulsive',
    'Conceited',
    'Condemnatory',
    'Conformist',
    'Confused',
    'Contemptible',
    'Conventional',
    'Cowardly',
    'Crafty',
    'Crass',
    'Crazy',
    'Criminal',
    'Critical',
    'Crude',
    'Cruel',
    'Cynical',
    'Decadent',
    'Deceitful',
    'Delicate',
    'Demanding',
    'Dependent',
    'Desperate',
    'Destructive',
    'Devious',
    'Difficult',
    'Dirty',
    'Disconcerting',
    'Discontented',
    'Discouraging',
    'Discourteous',
    'Dishonest',
    'Disloyal',
    'Disobedient',
    'Disorderly',
    'Disorganized',
    'Disputatious',
    'Disrespectful',
    'Disruptive',
    'Dissolute',
    'Dissonant',
    'Distractible',
    'Disturbing',
    'Dogmatic',
    'Domineering',
    'Dull',
    'Easily Discouraged',
    'Egocentric',
    'Enervated',
    'Envious',
    'Erratic',
    'Escapist',
    'Excitable',
    'Expedient',
    'Extravagant',
    'Extreme',
    'Faithless',
    'False',
    'Fanatical',
    'Fanciful',
    'Fatalistic',
    'Fawning',
    'Fearful',
    'Fickle',
    'Fiery',
    'Fixed',
    'Flamboyant',
    'Foolish',
    'Forgetful',
    'Fraudulent',
    'Frightening',
    'Frivolous',
    'Gloomy',
    'Graceless',
    'Grand',
    'Greedy',
    'Grim',
    'Gullible',
    'Hateful',
    'Haughty',
    'Hedonistic',
    'Hesitant',
    'Hidebound',
    'High-handed',
    'Hostile',
    'Ignorant',
    'Imitative',
    'Impatient',
    'Impractical',
    'Imprudent',
    'Impulsive',
    'Inconsiderate',
    'Incurious',
    'Indecisive',
    'Indulgent',
    'Inert',
    'Inhibited',
    'Insecure',
    'Insensitive',
    'Insincere',
    'Insulting',
    'Intolerant',
    'Irascible',
    'Irrational',
    'Irresponsible',
    'Irritable',
    'Lazy',
    'Libidinous',
    'Loquacious',
    'Malicious',
    'Mannered',
    'Mannerless',
    'Mawkish',
    'Mealymouthed',
    'Mechanical',
    'Meddlesome',
    'Melancholic',
    'Meretricious',
    'Messy',
    'Miserable',
    'Miserly',
    'Misguided',
    'Mistaken',
    'Money-minded',
    'Monstrous',
    'Moody',
    'Morbid',
    'Muddle-headed',
    'Naive',
    'Narcissistic',
    'Narrow',
    'Narrow-minded',
    'Natty',
    'Negativistic',
    'Neglectful',
    'Neurotic',
    'Nihilistic',
    'Obnoxious',
    'Obsessive',
    'Obvious',
    'Odd',
    'Offhand',
    'One-dimensional',
    'One-sided',
    'Opinionated',
    'Opportunistic',
    'Oppressed',
    'Outrageous',
    'Overimaginative',
    'Paranoid',
    'Passive',
    'Pedantic',
    'Perverse',
    'Petty',
    'Pharissical',
    'Phlegmatic',
    'Plodding',
    'Pompous',
    'Possessive',
    'Power-hungry',
    'Predatory',
    'Prejudiced',
    'Presumptuous',
    'Pretentious',
    'Prim',
    'Procrastinating',
    'Profligate',
    'Provocative',
    'Pugnacious',
    'Puritanical',
    'Quirky',
    'Reactionary',
    'Reactive',
    'Regimental',
    'Regretful',
    'Repentant',
    'Repressed',
    'Resentful',
    'Ridiculous',
    'Rigid',
    'Ritualistic',
    'Rowdy',
    'Ruined',
    'Sadistic',
    'Sanctimonious',
    'Scheming',
    'Scornful',
    'Secretive',
    'Sedentary',
    'Selfish',
    'Self-indulgent',
    'Shallow',
    'Shortsighted',
    'Shy',
    'Silly',
    'Single-minded',
    'Sloppy',
    'Slow',
    'Sly',
    'Small-thinking',
    'Softheaded',
    'Sordid',
    'Steely',
    'Stiff',
    'Strong-willed',
    'Stupid',
    'Submissive',
    'Superficial',
    'Superstitious',
    'Suspicious',
    'Tactless',
    'Tasteless',
    'Tense',
    'Thievish',
    'Thoughtless',
    'Timid',
    'Transparent',
    'Treacherous',
    'Trendy',
    'Troublesome',
    'Unappreciative',
    'Uncaring',
    'Uncharitable',
    'Unconvincing',
    'Uncooperative',
    'Uncreative',
    'Uncritical',
    'Unctuous',
    'Undisciplined',
    'Unfriendly',
    'Ungrateful',
    'Unhealthy',
    'Unimaginative',
    'Unimpressive',
    'Unlovable',
    'Unpolished',
    'Unprincipled',
    'Unrealistic',
    'Unreflective',
    'Unreliable',
    'Unrestrained',
    'Unself-critical',
    'Unstable',
    'Vacuous',
    'Vague',
    'Venal',
    'Venomous',
    'Vindictive',
    'Vulnerable',
    'Weak',
    'Weak-willed',
    'Well-meaning',
    'Willful',
    'Wishful',
    'Zany',
]
